version: "2.2"
services:
  # The even-streaming platform consisting of one zookeeper and one broker 
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "0001:0001"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "0002:0002"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
      - KAFKA_CFG_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # The Stream Processor. Apache Spark will be used in this project 
  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    ports:
      - "0003:0003"
    volumes:
      - "./spark:/opt/bitnami/data/"
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker
    environment:
      - SPARK_WORKER_CORES=1 
      - SPARK_WORKER_MEMORY=512m 
    ports:
      - "0004:0004"
    volumes:
      - "./spark:/opt/bitnami/data/"
    depends_on: 
      - spark-master

  # The relational databases for persisting the processed data 
  postgres:
    image: debezium/postgres:15
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0005:0005"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # The Monitoring Stack. Prometheus for monitoring and grafana for visualizations 
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    ports:
      - "0006:0006"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.4.0
    container_name: grafana 
    ports:
      - "0007:0007"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=arnold 
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
        
    
