version: '3.8'
services:
  # PostgresQL db and pgadmin interactive dashboard
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:15.4.0
    restart: always
    environment:
      POSTGRES_DB: product_matcher
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: opiyo123
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "opiyo@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "arnold1108"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # Standalone Kafka Cluster for streaming events 
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.9.0 
    restart: always
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports: 
      - "2181:2181"

  kafka:
    container_name: kafka 
    image: bitnami/kafka:3.4.1
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181" 
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT://localhost:29092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT://:29092"
    ports:
      - "29092:29092"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:cca2c9699755c2128bb88cf8920c9ed4414dbd58
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTER_NAME: local 
      KAFKA_CLUSTER_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8081:8081"
volumes:  
  postgresql_data:
  pgadmin-data:
