server:
  port: 8080
spring:
  application:
    name: GATEWAY-SVC
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:



axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson