server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: GATEWAY-SVC
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson