server:
  port: 8580
spring:
  application:
    name: STORE-SVC
  codec:
    max-in-memory-size: 3MB
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: store_svc
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson