server:
  port: 8180
spring:
  application:
    name: ACCOUNTS-SVC
  codec:
    max-in-memory-size: 3MB
  datasource:
    url: jdbc:postgresql://localhost:55000/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson