server:
  port: 8280
spring:
  application:
    name: CART-SVC
  codec:
    max-in-memory-size: 3MB
  datasource:
    password: opiyo123
    username: adventure
    url: jdbc:postgresql://localhost:5432/product_matcher
  jpa:
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    events: jackson
    general: jackson
    messages: jackson
